### ISSUE TITLE
Can't find dgm200_utm32s.asc file in Day11_Elevation

### ISSUE THREAD

**Issue by CNFeffery** [z3tt/30DayMapChallenge2019#1]
Can't find `dgm200_utm32s.asc` of the `Day11_Elevation`  example in this repository 😢

**Comment by z3tt** [comment]
It's too large to be hosted on GitHub, you can download it [here](https://gdz.bkg.bund.de/index.php/default/digitales-gelandemodell-gitterweite-200-m-dgm200.html).
